# Generated by Django 3.2.10 on 2022-01-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment_app', '0002_alter_student_data_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='date_enrolled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
